import ObjectiveC
import Tauri
import UIKit

/// Wire shape of `registerForPush` and the `pushToken` event; `environment`
/// is `"sandbox"` or `"production"` (see `PushRegistration.currentEnvironment`).
struct PushTokenPayload: Encodable {
  let token: String
  let environment: String
}

struct PushRegistrationError: LocalizedError {
  let message: String
  var errorDescription: String? { message }
}

/// Collects the APNs device token.
///
/// UIKit reports the token to the application delegate, and the delegate here
/// is generated by the Tauri/tao runtime, so there is no place to implement
/// `application(_:didRegisterForRemoteNotificationsWithDeviceToken:)`. The
/// two callbacks are attached to the delegate's class at runtime instead:
/// added when the class lacks them, wrapped (original still called) when it
/// has them.
///
/// All state lives on the main actor; the ObjC callbacks hop there.
@MainActor
final class PushRegistration {
  static let shared = PushRegistration()

  /// Fired for tokens that arrive with nobody waiting on `register` — iOS may
  /// hand out a new token at any launch.
  var onToken: ((PushTokenPayload) -> Void)?

  private var waiters: [UUID: (Result<PushTokenPayload, Error>) -> Void] = [:]
  private var hooked = false

  /// Registers with APNs and resolves with the first token (or failure) iOS
  /// reports back. Rejects after `timeout` so a JS promise is never left
  /// hanging when the system stays silent (no network, missing entitlement).
  func register(timeout: TimeInterval = 15) async throws -> PushTokenPayload {
    installHooks()
    return try await withCheckedThrowingContinuation { continuation in
      let id = UUID()
      waiters[id] = { continuation.resume(with: $0) }
      UIApplication.shared.registerForRemoteNotifications()
      Task { @MainActor in
        try? await Task.sleep(nanoseconds: UInt64(timeout * 1_000_000_000))
        self.finish(id, .failure(PushRegistrationError(message: "timed out waiting for the APNs device token")))
      }
    }
  }

  private func finish(_ id: UUID, _ result: Result<PushTokenPayload, Error>) {
    waiters.removeValue(forKey: id)?(result)
  }

  fileprivate func received(token data: Data) {
    let payload = PushTokenPayload(token: Self.hex(data), environment: Self.currentEnvironment())
    let pending = waiters
    waiters.removeAll()
    if pending.isEmpty {
      onToken?(payload)
    } else {
      for waiter in pending.values { waiter(.success(payload)) }
    }
  }

  fileprivate func failed(_ error: Error) {
    let pending = waiters
    waiters.removeAll()
    for waiter in pending.values { waiter(.failure(error)) }
  }

  static func hex(_ data: Data) -> String {
    data.map { String(format: "%02x", $0) }.joined()
  }

  /// Which APNs endpoint this build's token belongs to. Development and ad-hoc
  /// builds embed a provisioning profile whose `aps-environment` says so;
  /// TestFlight and App Store builds have no embedded profile and always use
  /// production.
  static func currentEnvironment() -> String {
    guard
      let url = Bundle.main.url(forResource: "embedded", withExtension: "mobileprovision"),
      let data = try? Data(contentsOf: url)
    else { return "production" }
    return environment(inProfile: data)
  }

  /// The profile is a CMS envelope around a plist; the plist text is plain
  /// inside it, so a text search is enough and avoids a CMS parser.
  static func environment(inProfile data: Data) -> String {
    let text = String(decoding: data, as: UTF8.self)
    guard
      let key = text.range(of: "<key>aps-environment</key>"),
      let value = text.range(of: "<string>", range: key.upperBound..<text.endIndex)
    else { return "production" }
    return text[value.upperBound...].hasPrefix("development") ? "sandbox" : "production"
  }

  private func installHooks() {
    guard !hooked, let delegate = UIApplication.shared.delegate, let cls = object_getClass(delegate) else { return }
    hooked = true

    let success = #selector(UIApplicationDelegate.application(_:didRegisterForRemoteNotificationsWithDeviceToken:))
    let successBlock: @convention(block) (AnyObject, UIApplication, Data) -> Void = { _, _, token in
      Task { @MainActor in PushRegistration.shared.received(token: token) }
    }
    Self.attach(to: cls, selector: success, block: successBlock) { original in
      let wrapped: @convention(block) (AnyObject, UIApplication, Data) -> Void = { this, app, token in
        Task { @MainActor in PushRegistration.shared.received(token: token) }
        typealias Fn = @convention(c) (AnyObject, Selector, UIApplication, Data) -> Void
        unsafeBitCast(original, to: Fn.self)(this, success, app, token)
      }
      return wrapped
    }

    let failure = #selector(UIApplicationDelegate.application(_:didFailToRegisterForRemoteNotificationsWithError:))
    let failureBlock: @convention(block) (AnyObject, UIApplication, Error) -> Void = { _, _, error in
      Task { @MainActor in PushRegistration.shared.failed(error) }
    }
    Self.attach(to: cls, selector: failure, block: failureBlock) { original in
      let wrapped: @convention(block) (AnyObject, UIApplication, Error) -> Void = { this, app, error in
        Task { @MainActor in PushRegistration.shared.failed(error) }
        typealias Fn = @convention(c) (AnyObject, Selector, UIApplication, Error) -> Void
        unsafeBitCast(original, to: Fn.self)(this, failure, app, error)
      }
      return wrapped
    }
  }

  /// Adds `block` as the implementation of `selector` on `cls`, or — when the
  /// class already implements it — replaces it with what `wrap` builds around
  /// the original implementation.
  private static func attach(to cls: AnyClass, selector: Selector, block: Any, wrap: (IMP) -> Any) {
    let types = "v@:@@"
    guard let method = class_getInstanceMethod(cls, selector) else {
      class_addMethod(cls, selector, imp_implementationWithBlock(block), types)
      return
    }
    let original = method_getImplementation(method)
    let wrapped = imp_implementationWithBlock(wrap(original))
    if hasOwnMethod(cls, selector) {
      method_setImplementation(method, wrapped)
    } else {
      // Only a superclass implements it: shadow it here rather than patching
      // the superclass for every other subclass.
      class_addMethod(cls, selector, wrapped, types)
    }
  }

  private static func hasOwnMethod(_ cls: AnyClass, _ selector: Selector) -> Bool {
    var count: UInt32 = 0
    guard let list = class_copyMethodList(cls, &count) else { return false }
    defer { free(list) }
    return (0..<Int(count)).contains { method_getName(list[$0]) == selector }
  }
}
